### ISSUE TITLE
ultrasound

### ISSUE THREAD

**Issue by todocono** [jieyouxu/koding-kreators-mblock-extension#3]
returns distance in cm

**Comment by jieyouxu** [comment]
Are the ultrasonic sensors only analog pins 7 and 6 (A7, A6)? It would seem like that way from the schematic, but just to be sure...
Edit: digital pins* D7 and D6?

**Comment by todocono** [comment]
We could connect it somewhere else, but now it’s on digital pins 6 & 7. Like the schematic

**Comment by todocono** [comment]
D7 & D6

2018-06-30 18:31 GMT+08:00 Jieyou Xu (Joe) <notifications@github.com>:

**Comment by jieyouxu** [comment]
The current implementation of this wrapper hard-codes D7 and D6 pins as the trigger and echo pins respectively, see the [1.6.0 release](https://github.com/jieyouxu/koding-kreators-mblock-extension/releases/tag/V1.6.0) for more information.
