### ISSUE TITLE
Servo

### ISSUE THREAD

**Issue by todocono** [jieyouxu/koding-kreators-mblock-extension#4]
this is a wrapper of the srevo angle but has the pin already in. The user selects servo1 and it points to pin 11 and servo2 goes to pin 10

**Comment by jieyouxu** [comment]
Current plan to implement this wrapper is to have a write block:
- `set servo #${n} to speed ${d}` where `${n}` is either of (1, 2) and `${d}` is any integer between the range of [-90, 90].
There could be an alternative "easy version" which supports three modes: `FORWARD`, `STOP`, or `REVERSE`.
- `set servo #${n} to mode ${m}` where `${n}` is either of (1, 2) and `${m}` is one of (`FORWARD`, `STOP`, `REVERSE`).

**Comment by jieyouxu** [comment]
Current servo motor wrapper block implementations are complete; see [release 1.7.0](https://github.com/jieyouxu/koding-kreators-mblock-extension/releases/tag/V1.7.0) for further information.
