### ISSUE TITLE
tone

### ISSUE THREAD

**Issue by todocono** [jieyouxu/koding-kreators-mblock-extension#5]
initial code should just address pin3 for the buzzer. 

conflict with IRreceive, something to consider when we start using remote control. Code should have something like:

void playTone(int tone, int duration) {
  for (long i = 0; i < duration * 1000L; i += tone * 2) {
    digitalWrite(speakerPin, HIGH);
    delayMicroseconds(tone);
    digitalWrite(speakerPin, LOW);
    delayMicroseconds(tone);
  }
}

**Comment by jieyouxu** [comment]
Initial support for speaker provided as of [version 1.9.0](https://github.com/jieyouxu/koding-kreators-mblock-extension/releases/tag/V1.9.0).
