### ISSUE TITLE
Touch

### ISSUE THREAD

**Issue by todocono** [jieyouxu/koding-kreators-mblock-extension#6]
-nice to have-

It would be interesting to explore why the capacitive sensing doesn't work: https://github.com/PaulStoffregen/CapacitiveSensor/blob/master/CapacitiveSensor.h

if it works, we could add a block that says "touch"

**Comment by jieyouxu** [comment]
Hardware issue: lack of resistor between analog pin A5 and sensor. Closed for now pending future hardware modifications.
