### ISSUE TITLE
read sensor

### ISSUE THREAD

**Issue by todocono** [jieyouxu/koding-kreators-mblock-extension#7]
I am not sure if it's my installation but right now it shows "read analog A(0)" . This should be replaced by Read Sensor ( ) , allowing to select from 1 to 4

**Comment by jieyouxu** [comment]
Currently this is addressed by four `read analog sensor #${n}` blocks where `${n}` is 1-4. Current plan is to modify the four different blocks and merge them into one single block supporting drop down selection menu from 1-4.

![screen shot 2018-06-30 at 16 40 40](https://user-images.githubusercontent.com/39484203/42123447-c83a37c6-7c84-11e8-8556-6821da332bb8.png)

**Comment by todocono** [comment]
Awesome!

2018-06-30 16:44 GMT+08:00 Jieyou Xu (Joe) <notifications@github.com>:

**Comment by jieyouxu** [comment]
The `read analog sensor` block has been optimized into one block with a dropdown selection menu with options (1, 2, 3, 4) as per [version 1.3.0](https://github.com/jieyouxu/koding-kreators-mblock-extension/releases/tag/V1.3.0).

![screen shot 2018-06-30 at 17 44 26](https://user-images.githubusercontent.com/39484203/42123950-43904c78-7c8d-11e8-984c-c5e4c4297349.png)
