### ISSUE TITLE
Potentiometer

### ISSUE THREAD

**Issue by todocono** [jieyouxu/koding-kreators-mblock-extension#9]
I found today "knob" was not working. It's possible it was that particular board. Could we double check?

**Comment by jieyouxu** [comment]
I've used the potentiometer many times. I think it's the particular board.

**Comment by jieyouxu** [comment]
See [here](https://github.com/jieyouxu/koding-kreators-mblock-extension/blob/1085f1f48ab951af5bc907f92afd27771910a20c/kodingkreators.s2e#L42) for the definition of the `read potentiometer (knob)` block.

**Comment by jieyouxu** [comment]
The JavaScript definition for that is [here](https://github.com/jieyouxu/koding-kreators-mblock-extension/blob/1085f1f48ab951af5bc907f92afd27771910a20c/js/kodingkreators.js#L132). They all seem okay to me.

**Comment by jieyouxu** [comment]
Tested the potentiometer block and it does work for the board that I tested it with.
 Possible issues:
- Upgrade firmware
- USB serial driver issue (disconnected / not connecting properly)
- mBlock UI thread / I/O thread hanged
